---
title: 异常和异常处理 - C# 编程指南
description: 了解异常和异常处理情况。 这些 C# 功能可帮助处理程序在运行时出现的意外或异常情况。
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#]
- exceptions [C#]
- C# language, exceptions
ms.assetid: 0001887f-4fa2-47e2-8034-2819477e2344
ms.openlocfilehash: 4be327be4e183d60e440358254aeb9c68fcf25ca
ms.sourcegitcommit: 6f58a5f75ceeb936f8ee5b786e9adb81a9a3bee9
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 07/28/2020
ms.locfileid: "87303382"
---
# <a name="exceptions-and-exception-handling-c-programming-guide"></a><span data-ttu-id="2a9cc-104">异常和异常处理（C# 编程指南）</span><span class="sxs-lookup"><span data-stu-id="2a9cc-104">Exceptions and Exception Handling (C# Programming Guide)</span></span>

<span data-ttu-id="2a9cc-105">C# 语言的异常处理功能有助于处理在程序运行期间发生的任何意外或异常情况。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-105">The C# language's exception handling features help you deal with any unexpected or exceptional situations that occur when a program is running.</span></span> <span data-ttu-id="2a9cc-106">异常处理功能使用 `try`、`catch` 和 `finally` 关键字来尝试执行可能失败的操作、在你确定合理的情况下处理故障，以及在事后清除资源。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-106">Exception handling uses the `try`, `catch`, and `finally` keywords to try actions that may not succeed, to handle failures when you decide that it is reasonable to do so, and to clean up resources afterward.</span></span> <span data-ttu-id="2a9cc-107">公共语言运行时 (CLR)、.NET/第三方库或应用程序代码都可生成异常。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-107">Exceptions can be generated by the common language runtime (CLR), by .NET or third-party libraries, or by application code.</span></span> <span data-ttu-id="2a9cc-108">异常是使用 `throw` 关键字创建而成。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-108">Exceptions are created by using the `throw` keyword.</span></span>

<span data-ttu-id="2a9cc-109">在许多情况下，异常并不是由代码直接调用的方法抛出，而是由调用堆栈中再往下的另一方法抛出。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-109">In many cases, an exception may be thrown not by a method that your code has called directly, but by another method further down in the call stack.</span></span> <span data-ttu-id="2a9cc-110">如果出现这种情况，CLR 会展开堆栈，同时针对特定异常类型查找包含 `catch` 代码块的方法，并执行找到的首个此类 `catch` 代码块。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-110">When this happens, the CLR will unwind the stack, looking for a method with a `catch` block for the specific exception type, and it will execute the first such `catch` block that if finds.</span></span> <span data-ttu-id="2a9cc-111">如果在调用堆栈中找不到相应的 `catch` 代码块，将会终止进程并向用户显示消息。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-111">If it finds no appropriate `catch` block anywhere in the call stack, it will terminate the process and display a message to the user.</span></span>

<span data-ttu-id="2a9cc-112">在以下示例中，方法用于测试除数是否为零，并捕获相应的错误。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-112">In this example, a method tests for division by zero and catches the error.</span></span> <span data-ttu-id="2a9cc-113">如果没有异常处理功能，此程序将终止，并显示 **DivideByZeroException was unhandled** 错误。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-113">Without the exception handling, this program would terminate with a **DivideByZeroException was unhandled** error.</span></span>

[!code-csharp[csProgGuideExceptions#18](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#18)]

## <a name="exceptions-overview"></a><span data-ttu-id="2a9cc-114">异常概述</span><span class="sxs-lookup"><span data-stu-id="2a9cc-114">Exceptions Overview</span></span>

<span data-ttu-id="2a9cc-115">异常具有以下属性：</span><span class="sxs-lookup"><span data-stu-id="2a9cc-115">Exceptions have the following properties:</span></span>

- <span data-ttu-id="2a9cc-116">异常是最终全都派生自 `System.Exception` 的类型。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-116">Exceptions are types that all ultimately derive from `System.Exception`.</span></span>
- <span data-ttu-id="2a9cc-117">在可能抛出异常的语句周围使用 `try` 代码块。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-117">Use a `try` block around the statements that might throw exceptions.</span></span>
- <span data-ttu-id="2a9cc-118">在 `try` 代码块中出现异常后，控制流会跳转到调用堆栈中任意位置上的首个相关异常处理程序。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-118">Once an exception occurs in the `try` block, the flow of control jumps to the first associated exception handler that is present anywhere in the call stack.</span></span> <span data-ttu-id="2a9cc-119">在 C# 中，`catch` 关键字用于定义异常处理程序。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-119">In C#, the `catch` keyword is used to define an exception handler.</span></span>
- <span data-ttu-id="2a9cc-120">如果给定的异常没有对应的异常处理程序，那么程序会停止执行，并显示错误消息。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-120">If no exception handler for a given exception is present, the program stops executing with an error message.</span></span>
- <span data-ttu-id="2a9cc-121">除非可以处理异常并让应用程序一直处于已知状态，否则不捕获异常。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-121">Do not catch an exception unless you can handle it and leave the application in a known state.</span></span> <span data-ttu-id="2a9cc-122">如果捕获 `System.Exception`，则使用 `catch` 代码块末尾的 `throw` 关键字重新抛出异常。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-122">If you catch `System.Exception`, re-throw it using the `throw` keyword at the end of the `catch` block.</span></span>
- <span data-ttu-id="2a9cc-123">如果 `catch` 代码块定义异常变量，可以用它来详细了解所发生的异常类型。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-123">If a `catch` block defines an exception variable, you can use it to obtain more information about the type of exception that occurred.</span></span>
- <span data-ttu-id="2a9cc-124">使用 `throw` 关键字，程序可以显式生成异常。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-124">Exceptions can be explicitly generated by a program by using the `throw` keyword.</span></span>
- <span data-ttu-id="2a9cc-125">异常对象包含错误详细信息，如调用堆栈的状态和错误的文本说明。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-125">Exception objects contain detailed information about the error, such as the state of the call stack and a text description of the error.</span></span>
- <span data-ttu-id="2a9cc-126">即使有异常抛出，`finally` 代码块中的代码仍会执行。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-126">Code in a `finally` block is executed even if an exception is thrown.</span></span> <span data-ttu-id="2a9cc-127">使用 `finally` 代码块可释放资源。例如，关闭在 `try` 代码块中打开的任何流或文件。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-127">Use a `finally` block to release resources, for example to close any streams or files that were opened in the `try` block.</span></span>
- <span data-ttu-id="2a9cc-128">.NET 中的托管异常在 Win32 结构化异常处理机制的基础之上实现。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-128">Managed exceptions in .NET are implemented on top of the Win32 structured exception handling mechanism.</span></span> <span data-ttu-id="2a9cc-129">有关详细信息，请参阅[结构化异常处理 (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) 和[速成教程：深入了解 Win32 结构化异常处理](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm)。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-129">For more information, see [Structured Exception Handling (C/C++)](/cpp/cpp/structured-exception-handling-c-cpp) and [A Crash Course on the Depths of Win32 Structured Exception Handling](http://bytepointer.com/resources/pietrek_crash_course_depths_of_win32_seh.htm).</span></span>

## <a name="related-sections"></a><span data-ttu-id="2a9cc-130">相关章节</span><span class="sxs-lookup"><span data-stu-id="2a9cc-130">Related Sections</span></span>

<span data-ttu-id="2a9cc-131">要详细了解异常和异常处理，请参阅以下文章：</span><span class="sxs-lookup"><span data-stu-id="2a9cc-131">See the following articles for more information about exceptions and exception handling:</span></span>

- [<span data-ttu-id="2a9cc-132">使用异常</span><span class="sxs-lookup"><span data-stu-id="2a9cc-132">Using Exceptions</span></span>](using-exceptions.md)
- [<span data-ttu-id="2a9cc-133">异常处理</span><span class="sxs-lookup"><span data-stu-id="2a9cc-133">Exception Handling</span></span>](exception-handling.md)
- [<span data-ttu-id="2a9cc-134">创建和引发异常</span><span class="sxs-lookup"><span data-stu-id="2a9cc-134">Creating and Throwing Exceptions</span></span>](creating-and-throwing-exceptions.md)
- [<span data-ttu-id="2a9cc-135">编译器生成的异常</span><span class="sxs-lookup"><span data-stu-id="2a9cc-135">Compiler-Generated Exceptions</span></span>](compiler-generated-exceptions.md)
- [<span data-ttu-id="2a9cc-136">如何使用 try/catch 处理异常（C# 编程指南）</span><span class="sxs-lookup"><span data-stu-id="2a9cc-136">How to handle an exception using try/catch (C# Programming Guide)</span></span>](how-to-handle-an-exception-using-try-catch.md)
- [<span data-ttu-id="2a9cc-137">如何使用 finally 执行清理代码</span><span class="sxs-lookup"><span data-stu-id="2a9cc-137">How to execute cleanup code using finally</span></span>](how-to-execute-cleanup-code-using-finally.md)
- [<span data-ttu-id="2a9cc-138">如何捕捉非 CLS 异常</span><span class="sxs-lookup"><span data-stu-id="2a9cc-138">How to catch a non-CLS exception</span></span>](how-to-catch-a-non-cls-exception.md)

## <a name="c-language-specification"></a><span data-ttu-id="2a9cc-139">C# 语言规范</span><span class="sxs-lookup"><span data-stu-id="2a9cc-139">C# Language Specification</span></span>

<span data-ttu-id="2a9cc-140">有关详细信息，请参阅 [C# 语言规范](/dotnet/csharp/language-reference/language-specification/introduction)中的[异常](~/_csharplang/spec/exceptions.md)。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-140">For more information, see [Exceptions](~/_csharplang/spec/exceptions.md) in the [C# Language Specification](/dotnet/csharp/language-reference/language-specification/introduction).</span></span> <span data-ttu-id="2a9cc-141">该语言规范是 C# 语法和用法的权威资料。</span><span class="sxs-lookup"><span data-stu-id="2a9cc-141">The language specification is the definitive source for C# syntax and usage.</span></span>

## <a name="see-also"></a><span data-ttu-id="2a9cc-142">请参阅</span><span class="sxs-lookup"><span data-stu-id="2a9cc-142">See also</span></span>

- <xref:System.SystemException>
- [<span data-ttu-id="2a9cc-143">C# 编程指南</span><span class="sxs-lookup"><span data-stu-id="2a9cc-143">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="2a9cc-144">C# 关键字</span><span class="sxs-lookup"><span data-stu-id="2a9cc-144">C# Keywords</span></span>](../../language-reference/keywords/index.md)
- [<span data-ttu-id="2a9cc-145">throw</span><span class="sxs-lookup"><span data-stu-id="2a9cc-145">throw</span></span>](../../language-reference/keywords/throw.md)
- [<span data-ttu-id="2a9cc-146">try-catch</span><span class="sxs-lookup"><span data-stu-id="2a9cc-146">try-catch</span></span>](../../language-reference/keywords/try-catch.md)
- [<span data-ttu-id="2a9cc-147">try-finally</span><span class="sxs-lookup"><span data-stu-id="2a9cc-147">try-finally</span></span>](../../language-reference/keywords/try-finally.md)
- [<span data-ttu-id="2a9cc-148">try-catch-finally</span><span class="sxs-lookup"><span data-stu-id="2a9cc-148">try-catch-finally</span></span>](../../language-reference/keywords/try-catch-finally.md)
- [<span data-ttu-id="2a9cc-149">异常</span><span class="sxs-lookup"><span data-stu-id="2a9cc-149">Exceptions</span></span>](../../../standard/exceptions/index.md)
